### ISSUE TITLE
Plugin downloading fails with FileAlreadyExistsException after interrupted installations

### ISSUE THREAD

**Issue by mutcianm** [JetBrains/sbt-idea-plugin#38]

**Comment by mutcianm** [comment]
```
[error] java.nio.file.FileAlreadyExistsException: /home/miha/.intellij-hoconPluginIC/sdk/downloads/psiviewer-193-SNAPSHOT.zip
[error]         at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:450)
[error]         at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:263)
[error]         at java.base/java.nio.file.Files.move(Files.java:1421)
[error]         at org.jetbrains.sbtidea.download.FileDownloader.download(FileDownloader.scala:27)
[error]         at org.jetbrains.sbtidea.download.IdeaUpdater.updatePlugin$1(IdeaUpdater.scala:50)
[error]         at org.jetbrains.sbtidea.download.IdeaUpdater.$anonfun$updatePlugins$1(IdeaUpdater.scala:54)
[error]         at org.jetbrains.sbtidea.download.IdeaUpdater.$anonfun$updatePlugins$1$adapted(IdeaUpdater.scala:54)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at org.jetbrains.sbtidea.download.IdeaUpdater.updatePlugins(IdeaUpdater.scala:54)
[error]         at org.jetbrains.sbtidea.download.IdeaUpdater.updateIdeaAndPlugins(IdeaUpdater.scala:28)
[error]         at org.jetbrains.sbtidea.Init.$anonfun$buildSettings$12(Init.scala:58)
[error]         at org.jetbrains.sbtidea.Init.$anonfun$buildSettings$12$adapted(Init.scala:49)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
```
