### ISSUE TITLE
NumberFormatException when resolving JBR if intellijBuild is "LATEST-EAP-SNAPSHOT"

### ISSUE THREAD

**Issue by mutcianm** [JetBrains/sbt-idea-plugin#95]
```
java.lang.NumberFormatException: For input string: "LATEST-EAP-2147483647"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
at org.jetbrains.sbtidea.download.plugin.RepoPluginInstaller$.$anonfun$compareIdeaVersions$1(RepoPluginInstaller.scala:116)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at scala.collection.TraversableLike.map(TraversableLike.scala:285)
at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
at org.jetbrains.sbtidea.download.plugin.RepoPluginInstaller$.compareIdeaVersions(RepoPluginInstaller.scala:116)
at org.jetbrains.sbtidea.download.jbr.JbrBintrayResolver.getJbrKind(JbrBintrayResolver.scala:51)
at org.jetbrains.sbtidea.download.jbr.JbrBintrayResolver.$anonfun$resolve$2(JbrBintrayResolver.scala:20)
```

**Comment by mutcianm** [comment]
report from an outdated version, this is not an issue in 3.9.3+
